
import React from 'react';
import { DashboardData } from '../types';
import { IconInfo, IconMoreHorizontal } from './Icons';

interface DashboardProps {
  data: DashboardData;
  onClose: () => void;
}

const COLORS = ['#3B82F6', '#10B981', '#F59E0B', '#6366F1', '#EC4899'];

// --- Simple SVG Pie Chart ---
const SimplePieChart = ({ data }: { data: { label: string; value: number; color?: string }[] }) => {
  const total = data.reduce((sum, item) => sum + item.value, 0);
  let cumulativePercent = 0;

  return (
    <div className="flex flex-col sm:flex-row items-center justify-center space-y-6 sm:space-y-0 sm:space-x-8">
      <div className="relative w-48 h-48">
        <svg viewBox="0 0 100 100" className="transform -rotate-90 w-full h-full">
          {data.map((item, index) => {
            const percent = item.value / total;
            const dashArray = percent * 314; // 2 * pi * r (r=50) approx 314
            const offset = cumulativePercent * 314;
            cumulativePercent += percent;

            return (
              <circle
                key={index}
                cx="50"
                cy="50"
                r="40" // radius 40
                stroke={item.color || COLORS[index % COLORS.length]}
                strokeWidth="16"
                fill="none"
                strokeDasharray={`${dashArray} 314`}
                strokeDashoffset={-offset}
                className="transition-all duration-500 ease-out hover:opacity-80"
              />
            );
          })}
        </svg>
        <div className="absolute inset-0 flex items-center justify-center flex-col">
          <span className="text-2xl font-bold text-gray-700">{Math.round(total)}</span>
          <span className="text-xs text-gray-500">Total</span>
        </div>
      </div>
      <div className="space-y-3">
        {data.map((item, index) => (
          <div key={index} className="flex items-center space-x-3">
            <span className="w-3 h-3 rounded-full" style={{ backgroundColor: item.color || COLORS[index % COLORS.length] }}></span>
            <span className="text-sm font-medium text-gray-700">{item.label}</span>
            <span className="text-sm text-gray-400">{Math.round((item.value / total) * 100)}%</span>
          </div>
        ))}
      </div>
    </div>
  );
};

// --- Simple HTML/CSS Bar Chart ---
const SimpleBarChart = ({ data }: { data: { label: string; value: number }[] }) => {
  // Set Y-axis max scale to 5000 as requested, or higher if data exceeds it.
  const max = Math.max(5000, ...data.map(d => d.value));

  return (
    <div className="h-64 flex items-end justify-between space-x-2 pt-4">
      {data.map((item, index) => (
        // Added h-full and justify-end so the flex item fills the chart height
        // and the bar aligns to the bottom.
        <div key={index} className="flex flex-col items-center flex-1 group relative h-full justify-end">
          <div 
            className="w-full max-w-[60px] bg-blue-500 rounded-t-md hover:bg-blue-600 transition-all duration-300 relative group-hover:shadow-md"
            style={{ height: `${(item.value / max) * 100}%`, minHeight: '4px' }}
          >
             <div className="opacity-0 group-hover:opacity-100 absolute -top-8 left-1/2 transform -translate-x-1/2 bg-gray-800 text-white text-xs px-2 py-1 rounded transition-opacity whitespace-nowrap z-10">
                £{item.value.toLocaleString()}
             </div>
          </div>
          <span className="text-[10px] text-gray-500 mt-2 truncate w-full text-center px-1" title={item.label}>{item.label.split(' ')[0]}</span>
        </div>
      ))}
    </div>
  );
};

export const Dashboard = ({ data, onClose }: DashboardProps) => {
  return (
    <div className="animate-fade-in-up space-y-6">
      {/* Header for Dashboard View */}
      <div className="flex items-center justify-between">
        <div>
           <h2 className="text-2xl font-bold text-gray-900">{data.title}</h2>
           <p className="text-sm text-gray-500 mt-1">Generated by Smart Assistant based on your prompt.</p>
        </div>
        {/* Back button is in App toolbar */}
      </div>

      {/* Metrics Row */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        {data.metrics.map((metric, index) => (
          <div key={index} className="bg-white p-6 rounded-xl border border-gray-200 shadow-sm hover:shadow-md transition-shadow">
            <div className="flex justify-between items-start mb-2">
              <span className="text-sm font-medium text-gray-500">{metric.label}</span>
              <IconInfo className="w-4 h-4 text-gray-300" />
            </div>
            <div className="flex items-baseline space-x-2">
              <span className="text-2xl font-bold text-gray-900">{metric.value}</span>
            </div>
            {metric.change && (
              <div className={`mt-2 text-xs font-medium inline-flex items-center px-2 py-0.5 rounded-full ${
                metric.trend === 'up' ? 'bg-green-50 text-green-700' : 
                metric.trend === 'down' ? 'bg-red-50 text-red-700' : 'bg-gray-50 text-gray-600'
              }`}>
                {metric.trend === 'up' ? '↑ ' : metric.trend === 'down' ? '↓ ' : '• '}
                {metric.change}
                <span className="ml-1 text-gray-400 font-normal">vs last month</span>
              </div>
            )}
          </div>
        ))}
      </div>

      {/* Charts Row */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Pie Chart Card */}
        <div className="lg:col-span-1 bg-white p-6 rounded-xl border border-gray-200 shadow-sm">
          <div className="flex items-center justify-between mb-6">
            <h3 className="text-base font-semibold text-gray-900">Payment Methods</h3>
            <button className="text-gray-400 hover:text-gray-600"><IconMoreHorizontal /></button>
          </div>
          <SimplePieChart data={data.paymentMethodDistribution} />
        </div>

        {/* Column Chart Card */}
        <div className="lg:col-span-2 bg-white p-6 rounded-xl border border-gray-200 shadow-sm">
          <div className="flex items-center justify-between mb-6">
            <h3 className="text-base font-semibold text-gray-900">Top 5 Customers Sales</h3>
            <div className="flex space-x-2">
               <span className="text-xs font-medium px-2 py-1 bg-gray-100 rounded text-gray-600">Sales Volume</span>
            </div>
          </div>
          <SimpleBarChart data={data.topCustomers} />
        </div>
      </div>

      {/* Small Data Table */}
      <div className="bg-white rounded-xl border border-gray-200 shadow-sm overflow-hidden">
        <div className="px-6 py-4 border-b border-gray-200 flex justify-between items-center">
          <h3 className="text-base font-semibold text-gray-900">Recent High Value Transactions</h3>
          <button className="text-sm text-blue-600 font-medium hover:text-blue-800">View all</button>
        </div>
        <div className="overflow-x-auto">
          <table className="min-w-full divide-y divide-gray-200">
            <thead className="bg-[rgb(184,198,90)]">
              <tr>
                <th className="px-6 py-3 text-left text-xs font-medium text-white uppercase">Customer</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-white uppercase">Status</th>
                <th className="px-6 py-3 text-right text-xs font-medium text-white uppercase">Amount</th>
              </tr>
            </thead>
            <tbody className="bg-white divide-y divide-gray-200">
               {data.topCustomers.slice(0, 5).map((customer, i) => (
                  <tr key={i}>
                    <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">{customer.label}</td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm">
                        <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-green-100 text-green-800">
                          Charged
                        </span>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900 text-right">£{customer.value.toLocaleString()}</td>
                  </tr>
               ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};
