import React from 'react';
import { DashboardData } from '../types';
import { motion } from 'framer-motion';
import {
    IconInfo,
    IconMoreHorizontal,
    IconArrowRight,
    IconDownload,
    IconCalendar,
    IconFilter
} from './Icons';
import { RevenueChart, DistributionChart, TopCustomersChart } from './ModernCharts';
import { MOCK_REVENUE_DATA } from '../constants';

interface DashboardProps {
    data: DashboardData;
    onClose: () => void;
}

const containerVariants = {
    hidden: { opacity: 0 },
    visible: {
        opacity: 1,
        transition: {
            staggerChildren: 0.1
        }
    }
};

const itemVariants = {
    hidden: { opacity: 0, y: 20 },
    visible: { opacity: 1, y: 0 }
};

// --- Enhanced KPI Card ---
const KPICard = ({ metric, index }: { metric: any; index: number }) => {
    return (
        <motion.div
            variants={itemVariants}
            whileHover={{ y: -5, scale: 1.02 }}
            className="relative bg-white/80 backdrop-blur-xl p-6 rounded-2xl border border-white/20 shadow-[0_8px_30px_rgb(0,0,0,0.04)] overflow-hidden group"
        >
            {/* Glow Effect Background */}
            <div className={`absolute -inset-0.5 bg-gradient-to-r ${index === 0 ? 'from-blue-300 to-purple-300' :
                index === 1 ? 'from-gray-300 to-slate-300' :
                    index === 2 ? 'from-red-600 to-red-400' :
                        'from-indigo-300 to-pink-300'
                } opacity-0 group-hover:opacity-30 blur transition duration-500`} />

            <div className="relative z-10">
                <div className="flex justify-between items-start mb-4">
                    <span className="text-sm font-medium text-gray-500 group-hover:text-gray-900 transition-colors">{metric.label}</span>
                    <div className="p-2 bg-gray-50 rounded-lg group-hover:bg-white group-hover:shadow-sm transition-all duration-300">
                        <IconInfo className="w-4 h-4 text-gray-400 group-hover:text-blue-500" />
                    </div>
                </div>

                <div className="flex items-baseline gap-2">
                    <motion.span
                        initial={{ opacity: 0, scale: 0.5 }}
                        animate={{ opacity: 1, scale: 1 }}
                        transition={{ delay: 0.2 + (index * 0.1), type: "spring", stiffness: 100 }}
                        className="text-3xl font-bold text-gray-900 tracking-tight"
                    >
                        {metric.value}
                    </motion.span>
                </div>

                {metric.change && (
                    <div className={`mt-3 text-xs font-medium inline-flex items-center px-2.5 py-1 rounded-full border ${metric.trend === 'up' ? 'bg-gray-50 text-gray-700 border-gray-100' :
                        metric.trend === 'down' ? 'bg-red-50 text-red-700 border-red-100' : 'bg-gray-50 text-gray-600 border-gray-100'
                        }`}>
                        {metric.trend === 'up' ? '↑ ' : metric.trend === 'down' ? '↓ ' : '• '}
                        {metric.change}
                        <span className="ml-1 text-gray-400 font-normal">vs last month</span>
                    </div>
                )}
            </div>
        </motion.div>
    );
};

export const ModernDashboard = ({ data, onClose }: DashboardProps) => {
    return (
        <motion.div
            className="space-y-8"
            variants={containerVariants}
            initial="hidden"
            animate="visible"
        >
            {/* Header Section */}
            <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
                <div>
                    <motion.h2
                        className="text-3xl font-bold text-gray-900 tracking-tight"
                        initial={{ opacity: 0, x: -20 }}
                        animate={{ opacity: 1, x: 0 }}
                    >
                        {data.title}
                    </motion.h2>
                    <p className="text-gray-500 mt-1 flex items-center gap-2">
                        <span className="w-2 h-2 rounded-full bg-red-600 animate-pulse"></span>
                        Live Data • Generated by Smart Assistant
                    </p>
                </div>

                <div className="flex items-center gap-3">
                    <button className="flex items-center gap-2 px-4 py-2 bg-white border border-gray-200 rounded-lg text-sm font-medium text-gray-700 hover:bg-gray-50 transition-colors shadow-sm">
                        <IconCalendar className="w-4 h-4 text-gray-500" />
                        <span>Last 30 Days</span>
                    </button>
                    <button className="flex items-center gap-2 px-4 py-2 bg-blue-600 text-white rounded-lg text-sm font-medium hover:bg-blue-700 transition-colors shadow-sm hover:shadow-md">
                        <IconDownload className="w-4 h-4" />
                        <span>Export Report</span>
                    </button>
                </div>
            </div>

            {/* KPI Cards */}
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
                {data.metrics.map((metric, index) => (
                    <KPICard key={index} metric={metric} index={index} />
                ))}
            </div>

            {/* Main Charts Section */}
            <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
                {/* Revenue Trend - Spans 2 columns */}
                <motion.div
                    variants={itemVariants}
                    className="lg:col-span-2 bg-white p-6 rounded-2xl border border-gray-100 shadow-sm hover:shadow-md transition-shadow duration-300"
                >
                    <div className="flex items-center justify-between mb-6">
                        <div>
                            <h3 className="text-lg font-bold text-gray-900">Revenue Trend</h3>
                            <p className="text-sm text-gray-500">Income over time</p>
                        </div>
                        <button className="p-2 hover:bg-gray-100 rounded-lg transition-colors">
                            <IconMoreHorizontal className="w-5 h-5 text-gray-400" />
                        </button>
                    </div>
                    <RevenueChart data={MOCK_REVENUE_DATA} />
                </motion.div>

                {/* Payment Method Distribution */}
                <motion.div
                    variants={itemVariants}
                    className="lg:col-span-1 bg-white p-6 rounded-2xl border border-gray-100 shadow-sm hover:shadow-md transition-shadow duration-300"
                >
                    <div className="flex items-center justify-between mb-6">
                        <div>
                            <h3 className="text-lg font-bold text-gray-900">Payment Methods</h3>
                            <p className="text-sm text-gray-500">Transaction volume by type</p>
                        </div>
                        <button className="p-2 hover:bg-gray-100 rounded-lg transition-colors">
                            <IconMoreHorizontal className="w-5 h-5 text-gray-400" />
                        </button>
                    </div>
                    <DistributionChart data={data.paymentMethodDistribution} />
                </motion.div>
            </div>

            {/* Secondary Charts & Tables */}
            <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
                {/* Top Customers Bar Chart */}
                <motion.div
                    variants={itemVariants}
                    className="lg:col-span-1 bg-white p-6 rounded-2xl border border-gray-100 shadow-sm hover:shadow-md transition-shadow duration-300"
                >
                    <div className="flex items-center justify-between mb-6">
                        <div>
                            <h3 className="text-lg font-bold text-gray-900">Top Customers</h3>
                            <p className="text-sm text-gray-500">By sales volume</p>
                        </div>
                    </div>
                    <TopCustomersChart data={data.topCustomers} />
                </motion.div>

                {/* Recent Transactions Table */}
                <motion.div
                    variants={itemVariants}
                    className="lg:col-span-2 bg-white rounded-2xl border border-gray-100 shadow-sm overflow-hidden flex flex-col hover:shadow-md transition-shadow duration-300"
                >
                    <div className="p-6 border-b border-gray-100 flex justify-between items-center bg-gray-50/50">
                        <div>
                            <h3 className="text-lg font-bold text-gray-900">Recent High Value Transactions</h3>
                            <p className="text-sm text-gray-500">Transactions over £1,000</p>
                        </div>
                        <button className="text-sm text-blue-600 font-medium hover:text-blue-800 flex items-center gap-1 hover:gap-2 transition-all">
                            View all <IconArrowRight className="w-4 h-4" />
                        </button>
                    </div>
                    <div className="overflow-x-auto flex-1">
                        <table className="min-w-full divide-y divide-gray-100">
                            <thead className="bg-gray-50">
                                <tr>
                                    <th className="px-6 py-4 text-left text-xs font-semibold text-gray-500 uppercase tracking-wider">Customer</th>
                                    <th className="px-6 py-4 text-left text-xs font-semibold text-gray-500 uppercase tracking-wider">Status</th>
                                    <th className="px-6 py-4 text-right text-xs font-semibold text-gray-500 uppercase tracking-wider">Amount</th>
                                    <th className="px-6 py-4 text-right text-xs font-semibold text-gray-500 uppercase tracking-wider">Date</th>
                                </tr>
                            </thead>
                            <tbody className="bg-white divide-y divide-gray-100">
                                {data.topCustomers.slice(0, 5).map((customer, i) => (
                                    <tr key={i} className="hover:bg-blue-50/30 transition-colors group cursor-pointer">
                                        <td className="px-6 py-4 whitespace-nowrap">
                                            <div className="flex items-center">
                                                <div className="h-8 w-8 rounded-full bg-gradient-to-br from-blue-100 to-blue-200 flex items-center justify-center text-blue-700 font-bold text-xs mr-3">
                                                    {customer.label.charAt(0)}
                                                </div>
                                                <div className="text-sm font-medium text-gray-900">{customer.label}</div>
                                            </div>
                                        </td>
                                        <td className="px-6 py-4 whitespace-nowrap">
                                            <span className="inline-flex items-center px-2.5 py-1 rounded-full text-xs font-medium bg-gray-100 text-gray-800 border border-gray-200">
                                                <span className="w-1.5 h-1.5 rounded-full bg-gray-500 mr-1.5"></span>
                                                Charged
                                            </span>
                                        </td>
                                        <td className="px-6 py-4 whitespace-nowrap text-sm font-semibold text-gray-900 text-right">
                                            £{customer.value.toLocaleString()}
                                        </td>
                                        <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500 text-right">
                                            Today
                                        </td>
                                    </tr>
                                ))}
                            </tbody>
                        </table>
                    </div>
                </motion.div>
            </div>
        </motion.div>
    );
};
